### ISSUE TITLE
Add google analytics.

### ISSUE THREAD

**Issue by codetheorem** [Catalyst-IN/OpenSourceEvents-Frontend#115]
## Description
Add google analytics for better reviews.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by gauravchauhan2403** [comment]
assign this to me I will work on it

**Comment by anubhavsingh16** [comment]
@gauravchauhan2403 feel free to open new issues.

**Comment by gauravchauhan2403** [comment]
sir, can i get the link of this repo, where you have hosted this.

**Comment by anubhavsingh16** [comment]
Link of website ?

**Comment by gauravchauhan2403** [comment]
Yes

**Comment by anubhavsingh16** [comment]
https://opensourcefrontend.netlify.app/
