### ISSUE TITLE
Third month overlapping with footer in mobile view

### ISSUE THREAD

**Issue by aastha985** [Catalyst-IN/OpenSourceEvents-Frontend#123]
The third month is overlapping with the footer in mobile view. Can I fix this issue?
![issue](https://user-images.githubusercontent.com/55681187/84407372-61574500-ac28-11ea-8080-0343eb2d4f71.jpg)

**Comment by anubhavsingh16** [comment]
@aastha985 can you work on this issue?

**Comment by aastha985** [comment]
Sure, I'll work on it
