### ISSUE TITLE
Add hover into events

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#134]
## Description
Show the description of open source events by using hover property. So user gets more information and help through this platform.
And take the information about events from https://github.com/Catalyst-IN/Open-Source-Events.

## Mocks
https://github.com/Catalyst-IN/OpenSourceEvents-Frontend/pull/133

![issye](https://user-images.githubusercontent.com/47811606/86604870-90609c80-bfc3-11ea-8aeb-1c9e4be79666.png)

**Comment by m-code12** [comment]
@anubhavsingh16 I can implement this . Assign it to me.

**Comment by anubhavsingh16** [comment]
Send PR @m-code12

**Comment by m-code12** [comment]
I can see that it is implemented for the Jan and Feb month. I have to do it for the rest, right @anubhavsingh16 ???

**Comment by anubhavsingh16** [comment]
Yes @m-code12

**Comment by m-code12** [comment]
In which file, can I find the description of the events?

**Comment by m-code12** [comment]
In which file can I find the description of the events?

**Comment by anubhavsingh16** [comment]
https://github.com/Catalyst-IN/Open-Source-Events do not copy-paste all read and add only few important points of events.

**Comment by m-code12** [comment]
> Send PR @m-code12

I have made a pr #138
