### ISSUE TITLE
Font Variation in Navbar

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#142]
## Description
When we open the website font style of the navbar is changing after a second to another font style, We want to fix one font style for the complete page.

**Comment by adithyaakrishna** [comment]
I accessed the website but seems to be fine, It would be great if you can provide a screenshot :)

**Comment by anubhavsingh16** [comment]
it appears when internet is slow

**Comment by adithyaakrishna** [comment]
I guess it must be because the google fonts wouldn't be able to load. So technically this won't be a error imho

**Comment by anubhavsingh16** [comment]
> I guess it must be because the google fonts wouldn't be able to load. So technically this won't be a error imho

Yes I think you are right
