### ISSUE TITLE
Bug on hovering on Open Source events or Hackathons on home page

### ISSUE THREAD

**Issue by agrim19** [Catalyst-IN/OpenSourceEvents-Frontend#143]
The hovering to open the description works fine if the complete 'January' section of the page is visible, but if we scroll down and that is not visible, this happens:

![shortened](https://user-images.githubusercontent.com/55059285/90275576-253a9d80-de80-11ea-88dd-7b1f06629ea1.gif)

Now I've tried this just 4-5 times and it worked once. So probably my observation about the scroll is wrong. But the issue did show up at some times. 
PS: I'm not doing anything with my mouse in the video. I've left the trackpad as it is when hovering over an item.

**Comment by anubhavsingh16** [comment]
@agrim19 Can you work on this issue?

**Comment by agrim19** [comment]
> @agrim19 Can you work on this issue?

Hi. I've currently taken a break from open source for some time. If this can wait then Ill be happy to do this later, else could you assign to someone else? :)

**Comment by VaibhavDS19** [comment]
Can I try to fix this?

**Comment by abhinav5481** [comment]
Is it still open? Can I work on it as a participant in CrossWoc challenge?

**Comment by anubhavsingh16** [comment]
> Is it still open? Can I work on it as a participant in CrossWoc challenge?

Of cource you can.

**Comment by abhinav5481** [comment]
Okay then, please assign this to me.

**Comment by abhinav5481** [comment]
Hi,
I couldn't find the branch 'develop' mentioned in the 'readme.md' for setting up the project. 
![image](https://user-images.githubusercontent.com/60434542/107849898-3d39ac80-6e24-11eb-8f3b-1ec1114df737.png)


Could you please check if the 'readme.md' is up-to-date?
I'm creating a branch from master as of now to fix the assigned bug.  Will that be fine?

**Comment by anubhavsingh16** [comment]
Change `develop` to `master` in Readme as well. And send seprate PR for that.
