### ISSUE TITLE
Add auto changing quote

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#144]
## Description
Add famous quotes of Steve Jobs on the space between month and footer. And the quote is changing after 10 sec.

**Comment by chanchalpatil** [comment]
I'd like to add this feature , stated working on it.

**Comment by anubhavsingh16** [comment]
> I'd like to add this feature , started working on it.

Okk 👍

**Comment by chanchalpatil** [comment]
I managed to add the feature. But found some glitches. Looks like there are
some screen size issues to be fixed in code

**Comment by chanchalpatil** [comment]
Hey @anubhavsingh16  ,
I managed to add text transition. But looks like there are some screen issues with screen size specifications.

**Comment by anubhavsingh16** [comment]
Ok so add issue in issue list and send PR for same.
