### ISSUE TITLE
Clicking on the month section in the navbar produces no effect

### ISSUE THREAD

**Issue by AdityaJ7** [Catalyst-IN/OpenSourceEvents-Frontend#145]
Bug:
The  'months' id has not been assigned to any element, which makes the 'MONTH' button of the navbar irresponsive.

Possible fix:

Add 'months' id to the h2 element that contains Open Source Events and Hackathons, or maybe create another element for that purpose.

**Comment by Harshi7016** [comment]
Can I look into the issue and work on it?

**Comment by AdityaJ7** [comment]
> Can I look into the issue and work on it?
> I am new to opensource project, kindly help me out.
> Thanks

I guess this repo is dead

**Comment by anubhavsingh16** [comment]
@Harshi7016 send PR and assign anyone from the org. for review.

**Comment by shudhanshu03** [comment]
can i work on this issue ? @anubhavsingh16 .
just i'll make some changes in href , then it will show the months section.

**Comment by shudhanshu03** [comment]
Issue solved @anubhavsingh16 . Can i send the PR on 1st oct ie:- tomorrow , so that it will be counted in hacktoberfest 😅.

**Comment by anubhavsingh16** [comment]
> Issue solved @anubhavsingh16 . Can i send the PR on 1st oct ie:- tomorrow , so that it will be counted in hacktoberfest 😅.

yes of course 🖖
