### ISSUE TITLE
Adding more events to the list

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#146]
Add more Open-Source events to the list according to month.

**Comment by shudhanshu03** [comment]
@anubhavsingh16  Can i work on this feature ?

**Comment by Nirbhay1910** [comment]
Hi, pls assign this issue to me.

**Comment by gupta224** [comment]
Hey, i assign this to me, i am a part of CroosWoc.

**Comment by NEELAM244** [comment]
Hey, plz assign this to me

**Comment by pranabprohit** [comment]
Hi, I would like to work on this issue, can you please assign this issue to me.
