### ISSUE TITLE
Make content responsive for (Mobile view)

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#147]

**Comment by amycruz97** [comment]
Pls can I take it for hacktoberfest

**Comment by glowreeya-01** [comment]
@anubhavsingh16 Can I work on this please?

**Comment by coderburhan** [comment]
Can i work on this project?

**Comment by Shubhainder** [comment]
I can work on this project.

**Comment by anubhavsingh16** [comment]
Anyone can work/contribute on this just by sending appropriate PR.

**Comment by anubhavsingh16** [comment]
I can't assign this issue to one person, so anyone who solved this issue please send the PR ASAP.

**Comment by amycruz97** [comment]
i checked it and it is responsive on mobile view
what exactly or where exactly do you want to achieve the result

**Comment by anubhavsingh16** [comment]
![ssc](https://user-images.githubusercontent.com/47811606/94773267-0d3fbe80-03d9-11eb-8e45-581a8b399a6f.png)
please look at footer

**Comment by jeannienguyen** [comment]
@anubhavsingh16 For Hacktoberfest, can you add the "hacktoberfest" topic to this repository so that our PRs count? Thank you!

**Comment by anubhavsingh16** [comment]
> @anubhavsingh16 For Hacktoberfest, can you add the "hacktoberfest" topic to this repository so that our PRs count? Thank you!

When you send PR, Hacktoberfest portal automatically detects your PR.

**Comment by Archna29** [comment]
Can i work on this issue

**Comment by NEELAM244** [comment]
plz give me this opportunitiesto to work  on this project

**Comment by Amool-kk** [comment]
I can do this project
It will complete in 3-4 days

**Comment by anubhavsingh16** [comment]
Don't ask `Can i work on this issue` if you think you are able to solve this issue thn just wright `Im working on this issue` and send PR for same.

**Comment by Sloth-Panda** [comment]
I am working on this issue will be sending pr soon @anubhavsingh16 can you also add crossWoc tag to the issue?
