### ISSUE TITLE
Change the font of Hackathon and Open Source defination

### ISSUE THREAD

**Issue by anubhavsingh16** [Catalyst-IN/OpenSourceEvents-Frontend#156]
## Description
Change must look better and relative to other fonts(Decent and Uniform).

**Comment by NEELAM244** [comment]
I am working on this issues

**Comment by kanishkaa24** [comment]
Hey! Can I work on this issue?

**Comment by anubhavsingh16** [comment]
> Hey! Can I work on this issue?

yes you can
