### ISSUE TITLE
Integrate Welcome Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [Catalyst-IN/OpenSourceEvents-Frontend#157]
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time.
For reference, check out: https://github.com/apps/welcome

Please assign it to me as a part of Cross Woc.

**Comment by muthuannamalai12** [comment]
@anubhavsingh16  For the custom message shown by the welcome bot we need a code of conduct. So for that reason I have opened a issue for code of conduct file. Kindly assign me that #165 issue.

**Comment by Sloth-Panda** [comment]
@anubhavsingh16 , it's a good first issue sir.

**Comment by anubhavsingh16** [comment]
> @anubhavsingh16  For the custom message shown by the welcome bot we need a code of conduct. So for that reason I have opened a issue for code of conduct file. Kindly assign me that #165 issue.

Im not going to assign multiple issue to single contributor, so if you find that is countable than send PR for same

**Comment by muthuannamalai12** [comment]
> > @anubhavsingh16  For the custom message shown by the welcome bot we need a code of conduct. So for that reason I have opened a issue for code of conduct file. Kindly assign me that #165 issue.
> 
> Im not going to assign multiple issue to single contributor, so if you find that is countable than send PR for same

@anubhavsingh16 I have created a pull request

**Comment by Sloth-Panda** [comment]
> @anubhavsingh16 , it's a good first issue sir.


@anubhavsingh16  Let me explain sir. This welcome bot is actually a github app which you can download and configure in your repos that you want it to use in and for it to give message when anyone opens an issue or makes a pr, you need to have some custom message and that message comes from a configuration file(config.yml). So, its just a matter of you downloading the app from the link and also just copy pasting the config file on your repo and everything will work perfectly. It involves 0 coding.
