### ISSUE TITLE
Make content responsive for (Mobile view)

### ISSUE THREAD

**Issue by aashimgarg** [Catalyst-IN/OpenSourceEvents-Frontend#19]
## Description: 
Make `Home Page` content responsive for (Mobile view).

**Comment by anubhavsingh16** [comment]
@vinayaksh42 @codetheorem @Sapna2001 have a look at this issue.

**Comment by m-code12** [comment]
@aashimgar I would like to work on this issue .Could you assign me ?

**Comment by aashimgarg** [comment]
You can use Flexbox or grid.. Its totally up to you.

**Comment by m-code12** [comment]
I will use grid. I should make the changes in index.html , right ?? @aashimgarg

**Comment by aashimgarg** [comment]
yes @m-code12 . Go Ahead!!

**Comment by m-code12** [comment]
Earlier,in the Open Source and Hackathon section, the images and para were included in the same column , hence it wasn't looking that good in mobile view .
Now I have put them in different columns . Please have a look @aashimgarg 


![image](https://user-images.githubusercontent.com/53649201/84425385-18f75180-ac3f-11ea-9443-1447428a8f00.png)

**Comment by m-code12** [comment]
Is it fine @aashimgarg  ?? Should I proceed with it ?

**Comment by m-code12** [comment]
@aashimgarg Please review my pr #132
