### ISSUE TITLE
feat: Validate Contact form!

### ISSUE THREAD

**Issue by aashimgarg** [Catalyst-IN/OpenSourceEvents-Frontend#96]
## Description
Now we can enter vague details and press enter and it works.

**Comment by Sapna2001** [comment]
@aashimgarg in the form phone no and name validation is required, right?

**Comment by anubhavsingh16** [comment]
Not phone number only email and name.

**Comment by Sapna2001** [comment]
Email is already validated.
![Annotation 2020-05-25 234924](https://user-images.githubusercontent.com/56690856/82835698-76bb3800-9ee2-11ea-923f-2a0539caac67.png)

**Comment by anubhavsingh16** [comment]
@aashimgarg @Amankumar29

**Comment by Amankumar29** [comment]
i think having a validation of only numbers will be good in the phone no section will be good.

**Comment by aashimgarg** [comment]
> @aashimgarg @Amankumar29

try
 Name:- only alphabets.
 Email:- characters@character.domain
 Phone No:- only numbers with lengh less thn 15
 Message:- length greater than 10

**Comment by anubhavsingh16** [comment]
Hey, @Amankumar29 @aashimgarg solve this issue.

**Comment by aashimgarg** [comment]
> Hey, @Amankumar29 @aashimgarg solve this issue.

@anubhavsingh16 no-one is working?

**Comment by anubhavsingh16** [comment]
I don't know bro @aashimgarg

**Comment by anubhavsingh16** [comment]
I think @Sapna2001 is working on this issue.

**Comment by Sapna2001** [comment]
I haven't started working on this issue. If someone is free please do this issue as I have to read some articles to do this. Never done this before.

**Comment by aashimgarg** [comment]
I will complete it!

**Comment by swarajpure** [comment]
> 
> 
> I will complete it!

In case you haven't started yet, can I do this?

**Comment by aashimgarg** [comment]
> > I will complete it!
> 
> In case you haven't started yet, can I do this?

Go ahead @swarajpure
